name = "Genie"
uuid = "54a25026-8a20-41b4-b67d-7241a2be3bfb"
authors = ["Leonardo Di Bari"]
version = "1.0.0-DEV"

[deps]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
